/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./index.tsx",
    "./App.tsx",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
    "./utils/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'bg-background-light',
    'bg-background-dark',
    'text-text-light',
    'text-text-dark',
    'text-text-subtle-light',
    'text-text-subtle-dark',
    'font-display',
    'border-border-light',
    'border-border-dark',
    'bg-primary',
    'bg-secondary',
    'bg-accent',
    'text-primary',
    'text-secondary',
    'text-accent',
  ],
  theme: {
    extend: {
      colors: {
        primary: "#2DD4BF",
        secondary: "#F472B6",
        accent: "#FBBF24",
        "primary-darker": "#D97C8B",
        "background-light": "#FFFFFF",
        "background-dark": "#111827",
        "text-light": "#1F2937",
        "text-dark": "#F9FAFB",
        "text-subtle-light": "#525252",
        "text-subtle-dark": "#a3a3a3",
        "border-light": "#E5E7EB",
        "border-dark": "#374151",
      },
      fontFamily: {
        display: ["Lexend", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
  darkMode: "class",
}
